"""
Unit tests for debt transfer DM notifications.

Tests the message content generated by send_debt_transfer_dms
for various pre-existing balance scenarios between debtor and creditor.
"""
import pytest
from unittest.mock import AsyncMock, patch, MagicMock

from notification_service import send_debt_transfer_dms


GUILD_ID = "guild_1"
TRANSFERRER_ID = "transferrer_B"
DEBTOR_ID = "debtor_A"
CREDITOR_ID = "creditor_C"
TRANSFER_AMOUNT = 200


def _make_guild():
    guild = MagicMock()
    guild.get_member.side_effect = lambda uid: None
    return guild


def _name_plain_factory(guild, user_id):
    """Return readable names for test user IDs."""
    names = {
        TRANSFERRER_ID: "PlayerB",
        DEBTOR_ID: "PlayerA",
        CREDITOR_ID: "PlayerC",
    }
    return names.get(user_id, f"User {user_id}")


@pytest.fixture
def mock_bot():
    bot = MagicMock()
    bot.get_user.return_value = None
    user = AsyncMock()
    bot.fetch_user = AsyncMock(return_value=user)
    return bot


def _balance_lookup(debtor_to_transferrer_post, debtor_to_creditor_post):
    """Build a side_effect for get_balance_with given post-transfer balances."""
    async def _get_balance(guild_id, player_id, counterparty_id):
        if player_id == DEBTOR_ID and counterparty_id == TRANSFERRER_ID:
            return debtor_to_transferrer_post
        if player_id == DEBTOR_ID and counterparty_id == CREDITOR_ID:
            return debtor_to_creditor_post
        return 0
    return _get_balance


async def _run_transfer(mock_bot, debtor_to_transferrer_post, debtor_to_creditor_post, amount=TRANSFER_AMOUNT):
    """Run send_debt_transfer_dms and return (debtor_msg, creditor_msg)."""
    with patch("notification_service.send_dm", new_callable=AsyncMock) as mock_send_dm, \
         patch("notification_service.get_member_name_plain", side_effect=_name_plain_factory), \
         patch("notification_service.get_balance_with", side_effect=_balance_lookup(debtor_to_transferrer_post, debtor_to_creditor_post)):
        mock_send_dm.return_value = True
        await send_debt_transfer_dms(
            bot=mock_bot,
            guild=_make_guild(),
            guild_id=GUILD_ID,
            transferrer_id=TRANSFERRER_ID,
            debtor_id=DEBTOR_ID,
            creditor_id=CREDITOR_ID,
            amount=amount,
        )
        assert mock_send_dm.call_count == 2
        debtor_call = mock_send_dm.call_args_list[0]
        creditor_call = mock_send_dm.call_args_list[1]
        return debtor_call.args[2], creditor_call.args[2]


class TestDebtTransferDMs:
    """Tests for send_debt_transfer_dms message content."""

    @pytest.mark.asyncio
    async def test_no_prior_balance(self, mock_bot):
        """A and C owe 0 to each other before transfer. A now owes C the transfer amount."""
        # Post-transfer: A owes C 200, A owes B 0
        debtor_msg, creditor_msg = await _run_transfer(mock_bot, 0, -200)

        # Debtor (A) message
        assert debtor_msg.startswith("PlayerB transferred 200 tix of your debt to PlayerC.")
        assert "You no longer owe PlayerB" in debtor_msg
        assert "Previously you and PlayerC were settled" in debtor_msg
        assert "Now you owe PlayerC 200 tix" in debtor_msg

        # Creditor (C) message
        assert creditor_msg.startswith("PlayerB transferred 200 tix of PlayerA's debt to you.")
        assert "Previously you and PlayerA were settled" in creditor_msg
        assert "Now PlayerA owe you 200 tix" in creditor_msg

    @pytest.mark.asyncio
    async def test_debtor_already_owed_creditor(self, mock_bot):
        """A already owed C 100. Transfer adds 200 more, total 300."""
        # Post-transfer: A owes C 300, A owes B 0
        debtor_msg, creditor_msg = await _run_transfer(mock_bot, 0, -300)

        # Debtor (A) message
        assert "You no longer owe PlayerB" in debtor_msg
        assert "Previously you owed PlayerC 100 tix" in debtor_msg
        assert "Now you owe PlayerC 300 tix" in debtor_msg

        # Creditor (C) message
        assert "Previously PlayerA owed you 100 tix" in creditor_msg
        assert "Now PlayerA owe you 300 tix" in creditor_msg

    @pytest.mark.asyncio
    async def test_creditor_owed_debtor_less_than_transfer(self, mock_bot):
        """C owed A 50. Transfer of 200 results in A owing C 150."""
        # Pre: debtor_to_creditor = +50 (C owed A 50)
        # Post: +50 - 200 = -150 (A owes C 150)
        debtor_msg, creditor_msg = await _run_transfer(mock_bot, 0, -150)

        # Debtor (A) message
        assert "You no longer owe PlayerB" in debtor_msg
        assert "Previously PlayerC owed you 50 tix" in debtor_msg
        assert "Now you owe PlayerC 150 tix" in debtor_msg

        # Creditor (C) message
        assert "Previously you owed PlayerA 50 tix" in creditor_msg
        assert "Now PlayerA owe you 150 tix" in creditor_msg

    @pytest.mark.asyncio
    async def test_creditor_owed_debtor_equal_to_transfer(self, mock_bot):
        """C owed A 200. Transfer of 200 cancels out to 0."""
        # Pre: debtor_to_creditor = +200 (C owed A 200)
        # Post: +200 - 200 = 0
        debtor_msg, creditor_msg = await _run_transfer(mock_bot, 0, 0)

        # Debtor (A) message
        assert "You no longer owe PlayerB" in debtor_msg
        assert "Previously PlayerC owed you 200 tix" in debtor_msg
        assert "Now you and PlayerC are settled" in debtor_msg

        # Creditor (C) message
        assert "Previously you owed PlayerA 200 tix" in creditor_msg
        assert "Now you and PlayerA are settled" in creditor_msg

    @pytest.mark.asyncio
    async def test_creditor_owed_debtor_more_than_transfer(self, mock_bot):
        """C owed A 500. Transfer of 200 reduces it to C still owing A 300."""
        # Pre: debtor_to_creditor = +500 (C owed A 500)
        # Post: +500 - 200 = +300 (C still owes A 300)
        debtor_msg, creditor_msg = await _run_transfer(mock_bot, 0, 300)

        # Debtor (A) message
        assert "You no longer owe PlayerB" in debtor_msg
        assert "Previously PlayerC owed you 500 tix" in debtor_msg
        assert "Now PlayerC owe you 300 tix" in debtor_msg

        # Creditor (C) message
        assert "Previously you owed PlayerA 500 tix" in creditor_msg
        assert "Now you owe PlayerA 300 tix" in creditor_msg

    @pytest.mark.asyncio
    async def test_remaining_debt_to_transferrer(self, mock_bot):
        """Partial transfer — A still owes B some amount."""
        # A owed B 500, transferred 200 to C, still owes B 300
        debtor_msg, creditor_msg = await _run_transfer(mock_bot, -300, -200)

        # Debtor (A) message — still owes transferrer
        assert "You still owe PlayerB 300 tix" in debtor_msg
        assert "You no longer owe PlayerB" not in debtor_msg
        assert "Previously you and PlayerC were settled" in debtor_msg
        assert "Now you owe PlayerC 200 tix" in debtor_msg

        # Creditor (C) message — unaffected by A↔B remainder
        assert "Previously you and PlayerA were settled" in creditor_msg
        assert "Now PlayerA owe you 200 tix" in creditor_msg
