"""add ended_by_player_id to streak history tables

Revision ID: 091b849f11bc
Revises: fe5790224a61
Create Date: 2025-12-17 17:10:54.488361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091b849f11bc'
down_revision: Union[str, Sequence[str], None] = 'fe5790224a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfect_streak_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_by_player_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('win_streak_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_by_player_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('win_streak_history', schema=None) as batch_op:
        batch_op.drop_column('ended_by_player_id')

    with op.batch_alter_table('perfect_streak_history', schema=None) as batch_op:
        batch_op.drop_column('ended_by_player_id')

    # ### end Alembic commands ###
