"""add spaces_object_key to draft_session

Revision ID: 1311a160cb1e
Revises: 091b849f11bc
Create Date: 2025-12-20 00:21:56.224751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1311a160cb1e'
down_revision: Union[str, Sequence[str], None] = '091b849f11bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spaces_object_key', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_sessions', schema=None) as batch_op:
        batch_op.drop_column('spaces_object_key')

    # ### end Alembic commands ###
