"""add_order_of_white_lotus_draft_win_streak_tracking

Revision ID: 2b1a09d27fb6
Revises: eb357aa329f7
Create Date: 2026-01-04 22:52:36.102681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1a09d27fb6'
down_revision: Union[str, Sequence[str], None] = 'eb357aa329f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_streak_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('streak_length', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('ended_by_player_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_streak_history', schema=None) as batch_op:
        batch_op.create_index('idx_draft_streak_guild_ended', ['guild_id', 'ended_at'], unique=False)
        batch_op.create_index('idx_draft_streak_guild_started', ['guild_id', 'started_at'], unique=False)
        batch_op.create_index('idx_draft_streak_player_guild', ['player_id', 'guild_id'], unique=False)

    with op.batch_alter_table('leaderboard_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_win_streak_view_message_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('draft_win_streak_timeframe', sa.String(length=20), nullable=True))

    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_draft_win_streak', sa.Integer(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('current_draft_win_streak_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('longest_draft_win_streak', sa.Integer(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('team_drafts_won', sa.Integer(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('team_drafts_lost', sa.Integer(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('team_drafts_tied', sa.Integer(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_column('team_drafts_tied')
        batch_op.drop_column('team_drafts_lost')
        batch_op.drop_column('team_drafts_won')
        batch_op.drop_column('longest_draft_win_streak')
        batch_op.drop_column('current_draft_win_streak_started_at')
        batch_op.drop_column('current_draft_win_streak')

    with op.batch_alter_table('leaderboard_messages', schema=None) as batch_op:
        batch_op.drop_column('draft_win_streak_timeframe')
        batch_op.drop_column('draft_win_streak_view_message_id')

    with op.batch_alter_table('draft_streak_history', schema=None) as batch_op:
        batch_op.drop_index('idx_draft_streak_player_guild')
        batch_op.drop_index('idx_draft_streak_guild_started')
        batch_op.drop_index('idx_draft_streak_guild_ended')

    op.drop_table('draft_streak_history')
    # ### end Alembic commands ###
