"""add tournament standings message columns

Revision ID: 3bd9ba818a53
Revises: 67a56c21748e
Create Date: 2026-06-13 04:16:05.829110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd9ba818a53'
down_revision: Union[str, Sequence[str], None] = '67a56c21748e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standings_channel_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('standings_message_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('standings_message_id')
        batch_op.drop_column('standings_channel_id')

    # ### end Alembic commands ###
