"""add tournament format column

Revision ID: 423e6e2679bd
Revises: 3bd9ba818a53
Create Date: 2026-06-14 18:34:38.121509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423e6e2679bd'
down_revision: Union[str, Sequence[str], None] = '3bd9ba818a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.String(length=16), server_default=sa.text("'swiss'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('format')

    # ### end Alembic commands ###
