"""add enabled field to log_channels

Revision ID: 5275a13e916a
Revises: 8d7a8458f84b
Create Date: 2025-12-20 23:17:34.797283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5275a13e916a'
down_revision: Union[str, Sequence[str], None] = '8d7a8458f84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_channels', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
