"""add_debt_ledger_table

Revision ID: 5ef7f4412b85
Revises: 700c93310d8b
Create Date: 2026-01-06 15:05:34.964515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef7f4412b85'
down_revision: Union[str, Sequence[str], None] = '700c93310d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('counterparty_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debt_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_debt_ledger_balance_lookup', ['guild_id', 'player_id', 'counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debt_ledger_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debt_ledger_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debt_ledger_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debt_ledger_player_id'))
        batch_op.drop_index(batch_op.f('ix_debt_ledger_guild_id'))
        batch_op.drop_index(batch_op.f('ix_debt_ledger_counterparty_id'))
        batch_op.drop_index('ix_debt_ledger_balance_lookup')

    op.drop_table('debt_ledger')
    # ### end Alembic commands ###
