"""add dm_notifications to player_preferences

Revision ID: 665498258e65
Revises: 0c5c759a16d8
Create Date: 2025-10-14 19:54:29.752389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665498258e65'
down_revision: Union[str, Sequence[str], None] = '0c5c759a16d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('player_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dm_notifications', sa.Boolean(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_preferences', schema=None) as batch_op:
        batch_op.drop_column('dm_notifications')

    # ### end Alembic commands ###
