"""link draft sessions to tournament matches

Revision ID: 67a56c21748e
Revises: 7ba559169f47
Create Date: 2026-06-12 12:56:32.927966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a56c21748e'
down_revision: Union[str, Sequence[str], None] = '7ba559169f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tournament_match_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('tournament_rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pairings_channel_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pairings_message_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_rounds', schema=None) as batch_op:
        batch_op.drop_column('pairings_message_id')
        batch_op.drop_column('pairings_channel_id')

    with op.batch_alter_table('draft_sessions', schema=None) as batch_op:
        batch_op.drop_column('tournament_match_id')

    # ### end Alembic commands ###
