"""remove_ended_by_player_id_from_draft_streak_history

Revision ID: 6a69a2d84437
Revises: 2b1a09d27fb6
Create Date: 2026-01-04 23:36:05.996007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a69a2d84437'
down_revision: Union[str, Sequence[str], None] = '2b1a09d27fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_streak_history', schema=None) as batch_op:
        batch_op.drop_column('ended_by_player_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_streak_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_by_player_id', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
