"""add_starting_seat_to_quiz_sessions

Revision ID: 700c93310d8b
Revises: 6a69a2d84437
Create Date: 2026-01-06 00:00:19.173460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700c93310d8b'
down_revision: Union[str, Sequence[str], None] = '6a69a2d84437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_seat', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_column('starting_seat')

    # ### end Alembic commands ###
