"""add tournament rounds matches and participant stats

Revision ID: 7ba559169f47
Revises: f8254658189d
Create Date: 2026-06-12 12:26:02.966117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba559169f47'
down_revision: Union[str, Sequence[str], None] = 'f8254658189d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round_number', name='uq_tournament_round')
    )
    op.create_table('tournament_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('team_a_participant_id', sa.Integer(), nullable=False),
    sa.Column('team_b_participant_id', sa.Integer(), nullable=True),
    sa.Column('team_a_wins', sa.Integer(), nullable=True),
    sa.Column('team_b_wins', sa.Integer(), nullable=True),
    sa.Column('is_bye', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['tournament_rounds.id'], ),
    sa.ForeignKeyConstraint(['team_a_participant_id'], ['tournament_participants.id'], ),
    sa.ForeignKeyConstraint(['team_b_participant_id'], ['tournament_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_wins', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('match_losses', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('match_draws', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('points', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('game_wins', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('game_losses', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('byes', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_participants', schema=None) as batch_op:
        batch_op.drop_column('byes')
        batch_op.drop_column('game_losses')
        batch_op.drop_column('game_wins')
        batch_op.drop_column('points')
        batch_op.drop_column('match_draws')
        batch_op.drop_column('match_losses')
        batch_op.drop_column('match_wins')

    op.drop_table('tournament_matches')
    op.drop_table('tournament_rounds')
    # ### end Alembic commands ###
