"""add quiz points leaderboard columns

Revision ID: 8d7a8458f84b
Revises: ca34a161105c
Create Date: 2025-12-20 18:46:22.530283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7a8458f84b'
down_revision: Union[str, Sequence[str], None] = 'ca34a161105c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_points_view_message_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('quiz_points_timeframe', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard_messages', schema=None) as batch_op:
        batch_op.drop_column('quiz_points_timeframe')
        batch_op.drop_column('quiz_points_view_message_id')

    # ### end Alembic commands ###
