"""add per-match pairing message and thread columns

Revision ID: 935bb3b19df1
Revises: 423e6e2679bd
Create Date: 2026-06-15 00:44:58.103475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935bb3b19df1'
down_revision: Union[str, Sequence[str], None] = '423e6e2679bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pairings_channel_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pairings_message_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('thread_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_matches', schema=None) as batch_op:
        batch_op.drop_column('thread_id')
        batch_op.drop_column('pairings_message_id')
        batch_op.drop_column('pairings_channel_id')

    # ### end Alembic commands ###
