"""add side to stake pairings

Revision ID: 9fc50bb01c4c
Revises: cf93dc5532bb
Create Date: 2026-08-26 17:16:52.186188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc50bb01c4c'
down_revision: Union[str, Sequence[str], None] = 'cf93dc5532bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stake_pairings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('side_a', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('side_b', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###

    # json_each is SQLite's JSON table function; team_a is a JSON array of ids.
    #
    # Restricted to pairings whose draft session still EXISTS. 35 rows reference
    # a session that was deleted, leaving the pairing behind; without this guard
    # json_each(NULL) yields nothing and BOTH players resolve to 'B' -- a
    # same-side pairing that never happened. They are left NULL instead, which
    # is honest: their side is genuinely unknowable. They are also inert (no
    # session to settle, zero debts booked), and the settlement guard added in
    # Task 3 skips them because NULL == NULL.
    for col, player in (("side_a", "player_a_id"), ("side_b", "player_b_id")):
        op.execute(f"""
            UPDATE stake_pairings SET {col} = (
                SELECT CASE WHEN EXISTS (
                    SELECT 1 FROM draft_sessions d2, json_each(d2.team_a) j
                    WHERE d2.session_id = stake_pairings.session_id
                      AND j.value = stake_pairings.{player}
                ) THEN 'A' ELSE 'B' END
            )
            WHERE EXISTS (
                SELECT 1 FROM draft_sessions d
                WHERE d.session_id = stake_pairings.session_id
            )
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stake_pairings', schema=None) as batch_op:
        batch_op.drop_column('side_b')
        batch_op.drop_column('side_a')

    # ### end Alembic commands ###
