"""card lending library: one active loan per borrower

Revision ID: b6a7b0a90f12
Revises: tourneydrop01
Create Date: 2026-09-16 11:55:23.827857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a7b0a90f12'
down_revision: Union[str, Sequence[str], None] = 'tourneydrop01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('borrower_id', sa.String(length=64), nullable=False),
    sa.Column('cards', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('borrowed_at', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_loans', schema=None) as batch_op:
        batch_op.create_index('ix_card_loans_borrower', ['guild_id', 'borrower_id'], unique=False)
        batch_op.create_index('ix_card_loans_job', ['job_id'], unique=False, sqlite_where=sa.text('job_id IS NOT NULL'))
        batch_op.create_index('uq_card_loans_one_active_per_borrower', ['guild_id', 'borrower_id'], unique=True, sqlite_where=sa.text("state != 'returned'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_loans', schema=None) as batch_op:
        batch_op.drop_index('uq_card_loans_one_active_per_borrower', sqlite_where=sa.text("state != 'returned'"))
        batch_op.drop_index('ix_card_loans_job', sqlite_where=sa.text('job_id IS NOT NULL'))
        batch_op.drop_index('ix_card_loans_borrower')

    op.drop_table('card_loans')
    # ### end Alembic commands ###
