"""add ring bearer state table

Revision ID: c508fa5830d2
Revises: eb1c97a992da
Create Date: 2026-01-13 20:21:52.680541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c508fa5830d2'
down_revision: Union[str, Sequence[str], None] = 'eb1c97a992da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ring_bearer_state',
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('current_bearer_id', sa.String(length=64), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('acquired_via', sa.String(length=32), nullable=True),
    sa.Column('previous_bearer_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    with op.batch_alter_table('ring_bearer_state', schema=None) as batch_op:
        batch_op.create_index('idx_ring_bearer_guild', ['guild_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ring_bearer_state', schema=None) as batch_op:
        batch_op.drop_index('idx_ring_bearer_guild')

    op.drop_table('ring_bearer_state')
    # ### end Alembic commands ###
