"""add quiz tables

Revision ID: ca34a161105c
Revises: 1311a160cb1e
Create Date: 2025-12-20 15:51:39.460849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca34a161105c'
down_revision: Union[str, Sequence[str], None] = '1311a160cb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_sessions',
    sa.Column('quiz_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('draft_session_id', sa.String(length=128), nullable=False),
    sa.Column('pack_trace_data', sa.JSON(), nullable=False),
    sa.Column('correct_answers', sa.JSON(), nullable=False),
    sa.Column('posted_by', sa.String(length=64), nullable=False),
    sa.Column('posted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_participants', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('quiz_stats',
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('total_quizzes', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_picks_attempted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_picks_correct', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('accuracy_percentage', sa.Float(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('total_points', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('average_points_per_quiz', sa.Float(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('highest_quiz_score', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('current_perfect_streak', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('longest_perfect_streak', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_quiz_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('player_id', 'guild_id')
    )
    op.create_table('quiz_submissions',
    sa.Column('quiz_id', sa.String(length=64), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('guesses', sa.JSON(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('pick_1_correct', sa.Boolean(), nullable=False),
    sa.Column('pick_2_correct', sa.Boolean(), nullable=False),
    sa.Column('pick_3_correct', sa.Boolean(), nullable=False),
    sa.Column('pick_4_correct', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('pick_1_points', sa.Integer(), nullable=False),
    sa.Column('pick_2_points', sa.Integer(), nullable=False),
    sa.Column('pick_3_points', sa.Integer(), nullable=False),
    sa.Column('pick_4_points', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_sessions.quiz_id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_submissions')
    op.drop_table('quiz_stats')
    op.drop_table('quiz_sessions')
    # ### end Alembic commands ###
