"""add sign_up_history table

Revision ID: cbcd2bbfc0a9
Revises: a9c77df9cda3
Create Date: 2025-07-10 12:31:21.901191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcd2bbfc0a9'
down_revision: Union[str, Sequence[str], None] = 'a9c77df9cda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_up_history',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_display_name', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['draft_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sign_up_history')
    # ### end Alembic commands ###
