"""add quiz scheduling tables

Revision ID: ccce6cdc4528
Revises: 5275a13e916a
Create Date: 2025-12-20 23:42:40.481392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccce6cdc4528'
down_revision: Union[str, Sequence[str], None] = '5275a13e916a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_channels',
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('guild_id', sa.Text(), nullable=False),
    sa.Column('last_post', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_zone', sa.Text(), server_default=sa.text("'UTC'"), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('quiz_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('post_time', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['quiz_channels.channel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_schedules')
    op.drop_table('quiz_channels')
    # ### end Alembic commands ###
