"""card library: what a partial borrow is offering

Revision ID: e197552c0f87
Revises: cee22f56c29f
Create Date: 2026-09-16 14:06:41.262079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e197552c0f87'
down_revision: Union[str, Sequence[str], None] = 'b6a7b0a90f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_cards', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_loans', schema=None) as batch_op:
        batch_op.drop_column('pending_cards')

    # ### end Alembic commands ###
