"""add display_id to quiz_sessions

Revision ID: eb357aa329f7
Revises: ccce6cdc4528
Create Date: 2025-12-26 16:06:39.981547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb357aa329f7'
down_revision: Union[str, Sequence[str], None] = 'ccce6cdc4528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add display_id column and backfill with sequential IDs per guild."""

    # Step 1: Add column as nullable
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_id', sa.Integer(), nullable=True))

    # Step 2: Backfill display_ids based on chronological order per guild
    conn = op.get_bind()

    # Get all guilds with quizzes
    guilds = conn.execute(sa.text(
        "SELECT DISTINCT guild_id FROM quiz_sessions ORDER BY guild_id"
    )).fetchall()

    # For each guild, assign sequential IDs based on posted_at
    for (guild_id,) in guilds:
        quizzes = conn.execute(sa.text(
            "SELECT quiz_id FROM quiz_sessions "
            "WHERE guild_id = :guild_id "
            "ORDER BY posted_at ASC, quiz_id ASC"
        ), {"guild_id": guild_id}).fetchall()

        for idx, (quiz_id,) in enumerate(quizzes, start=1):
            conn.execute(sa.text(
                "UPDATE quiz_sessions SET display_id = :display_id "
                "WHERE quiz_id = :quiz_id"
            ), {"display_id": idx, "quiz_id": quiz_id})

    # Step 3: Make column non-nullable
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.alter_column('display_id',
                    existing_type=sa.Integer(),
                    nullable=False)

    # Step 4: Create unique composite index
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_quiz_sessions_guild_display_id', ['guild_id', 'display_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz_sessions_guild_display_id')
        batch_op.drop_column('display_id')

    # ### end Alembic commands ###
