"""add stake_pairings table for multiple stakes per player

Revision ID: ed98a1017dfe
Revises: c508fa5830d2
Create Date: 2026-02-06 17:00:23.595191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed98a1017dfe'
down_revision: Union[str, Sequence[str], None] = 'c508fa5830d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stake_pairings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('player_a_id', sa.String(length=64), nullable=False),
    sa.Column('player_b_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['draft_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stake_pairings', schema=None) as batch_op:
        batch_op.create_index('ix_stake_pairings_player_a', ['player_a_id'], unique=False)
        batch_op.create_index('ix_stake_pairings_player_b', ['player_b_id'], unique=False)
        batch_op.create_index('ix_stake_pairings_session', ['session_id'], unique=False)

    # ### end Alembic commands ###

    # Backfill existing stake data from stake_info table
    conn = op.get_bind()

    # Get all stake_info records with assigned stakes
    # Filter out NULL session_ids
    existing_stakes = conn.execute(sa.text(
        """
        SELECT session_id, player_id, opponent_id, assigned_stake
        FROM stake_info
        WHERE opponent_id IS NOT NULL
        AND assigned_stake IS NOT NULL
        AND session_id IS NOT NULL
        """
    )).fetchall()

    # Deduplicate and insert into stake_pairings
    # The old system had symmetric pairs where both players pointed to each other
    # We only need one record per pair in the new table
    processed = set()
    inserted_count = 0

    for session_id, player_id, opponent_id, amount in existing_stakes:
        # Create sorted pair key to avoid duplicates
        players = tuple(sorted([player_id, opponent_id]))
        pair_key = (session_id, players[0], players[1], amount)

        if pair_key in processed:
            continue
        processed.add(pair_key)

        # Insert pairing
        conn.execute(sa.text(
            """
            INSERT INTO stake_pairings (session_id, player_a_id, player_b_id, amount)
            VALUES (:session_id, :player_a, :player_b, :amount)
            """
        ), {
            "session_id": session_id,
            "player_a": players[0],
            "player_b": players[1],
            "amount": amount
        })
        inserted_count += 1

    print(f"Backfilled {inserted_count} stake pairings from stake_info table")

    # Note: We keep assigned_stake and opponent_id in stake_info for now
    # They'll be deprecated in a future migration after all code is updated


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stake_pairings', schema=None) as batch_op:
        batch_op.drop_index('ix_stake_pairings_session')
        batch_op.drop_index('ix_stake_pairings_player_b')
        batch_op.drop_index('ix_stake_pairings_player_a')

    op.drop_table('stake_pairings')
    # ### end Alembic commands ###
